/edep/gdml/read /sdf/home/s/sfogarty/Desktop/LArTPC_sim/geometries/Module0_steplimit.gdml
/edep/db/open tracklength_test.root
/edep/hitLength TPCActive_shape 0.00001 mm
/edep/hitLength TPCActive_shape 0.00001 mm
/edep/update
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 0.0 -22 0.0 cm
/gps/pos/halfx 30.2723 cm
/gps/pos/halfy 62.0543 cm
/gps/pos/halfz 31.0163 cm
/gps/ang/type iso
/gps/particle e-
/gps/energy 0.6 MeV
